---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - default-jre
      - default-jdk
      - unzip
    state: present
    update_cache: true
    force_apt_get: true

- name: Create necessary group
  ansible.builtin.group:
    name: kafka
    system: true
    state: present

- name: Create necessary user
  ansible.builtin.user:
    name: kafka
    system: true
    create_home: false
    shell: /usr/bin/false
    group: kafka
    state: present

- name: Download kafka package
  ansible.builtin.get_url:
    url: https://downloads.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz
    dest: /opt/kafka.tgz
    owner: root
    group: root
    mode: '0644'

- name: Extract and place the downlaoded package in correct path # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: 'tar -xf kafka.tgz && rm -rf kafka && mv kafka_2.13-2.6.0 kafka && rm kafka.tgz'
    warn: false
  register: extration_output
  args:
    chdir: '/opt'
  changed_when: extration_output.rc != 0

- name: Change the owner of kafka directory
  ansible.builtin.file:
    path: /opt/kafka
    recurse: true
    owner: kafka
    group: kafka
    mode: '0755'

- name: Add systemd services for zookeeper and kafka
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - zookeeper.service
    - kafka.service
  notify:
    - Enable Zookeeper Service
    - Enable Kafka Service
