- name: Enable Zookeeper Service
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
    daemon_reload: true
    enabled: true

- name: Enable Kafka Service
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    daemon_reload: true
    enabled: true
